version: '3.8'

services:
  vector-db-api:
    image: ghcr.io/blue-elephants-solutions-pte-ltd/vector-db-api:latest
    ports:
      - "2100:2100"
    volumes:
      - /var/www/VECTOR_DB:/app/VECTOR_DB
    environment:
      - PYTHONUNBUFFERED=1

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    volumes:
      - ai-assistant-qdrant:/qdrant/storage

volumes:
  ai-assistant-qdrant:
    external: true